### ISSUE TITLE
fedora-30-cloud-base box url is returning a 404

### ISSUE THREAD

**Issue by jelmew** [debezium/oracle-vagrant-box#14]
The readme says that you can simply run vagrant up to start the box.

However, vagrant up fails with the following error.  It seems the box is no longer available at the current URL. What is a suitable replacement?

`Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'fedora/30-cloud-base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'fedora/30-cloud-base'
    default: URL: https://vagrantcloud.com/fedora/30-cloud-base
==> default: Adding box 'fedora/30-cloud-base' (v30.20190425.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/fedora/boxes/30-cloud-base/versions/30.20190425.0/providers/virtualbox.box
Download redirected to host: download.fedoraproject.org
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 `

**Comment by jpechane** [comment]
@jelmew Hi, could you please try to change the Vagrantifle and use `fedora/33-cloud-base` or `fedora/32-cloud-base` instead of `fedora/3o-cloud-base`? If it works for you, could you please submit the change as a pull request?

Thanks

**Comment by jelmew** [comment]
It works, however fedora 32 uses podman. So I had to manually install docker. It requires a little bit more changes.

**Comment by carlosfvp** [comment]
> 
> 
> It works, however fedora 32 uses podman. So I had to manually install docker. It requires a little bit more changes.

Hi, can you please include the extra steps you made for fedora 32?

Thank you

**Comment by jpechane** [comment]
Fixed via https://github.com/debezium/oracle-vagrant-box/pull/19
