### ISSUE TITLE
Cannot set up logminer with 19.3.0.0

### ISSUE THREAD

**Issue by gordillo-ramon** [debezium/oracle-vagrant-box#20]
After `shutdown immediate`, it says:

```
ORA-01261: parameter db_recovery_file_dest destination string cannot be translated
```

which means /opt/oracle/oradata/recovery_area is not created, so this is an additional step to include in setup-logminer.sh before shutdown.

**Comment by Naros** [comment]
Hi @gordillo-ramon I believe this is covered in the `README.md`, see:
https://github.com/debezium/oracle-vagrant-box#permissions
